### ISSUE TITLE
Switch to extension methods rather than modules

### ISSUE THREAD

**Issue by Smaug123** [Smaug123/WoofWare.Myriad#60]
This allows us to add members from different generators simultaneously, without having to somehow disambiguate module names.

**Comment by Smaug123** [comment]
Done for JSON parsing in #63

**Comment by Smaug123** [comment]
Done for JSON serialisation in #69

**Comment by pleaseletmesearch** [comment]
For HttpClient pls

**Comment by Smaug123** [comment]
Done for HttpClient (to a limited extent, at least) in #140.

**Comment by Smaug123** [comment]
I claim we don't need this for any others.
